"""Abonelik ve Fatura tablolari eklendi

Revision ID: 48629f8bee0b
Revises: f7a8b9c1d2e3
Create Date: 2026-08-21 23:58:35.472119

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48629f8bee0b'
down_revision: Union[str, None] = 'f7a8b9c1d2e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
