"""add customer_interactions

Revision ID: 82a7617183aa
Revises: 6ae1a8c9ab65
Create Date: 2026-08-20 06:23:59.024499

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '82a7617183aa'
down_revision: Union[str, None] = '6ae1a8c9ab65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer_interactions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('product_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('interaction_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_interactions_phone'), 'customer_interactions', ['phone'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_customer_interactions_phone'), table_name='customer_interactions')
    op.drop_table('customer_interactions')
    # ### end Alembic commands ###
