"""Base_Products tablosuna created_at eklendi

Revision ID: 94bf5f2512c8
Revises: e5b3c2d1a4f6
Create Date: 2026-08-21 18:21:05.202010

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94bf5f2512c8'
down_revision: Union[str, None] = 'e5b3c2d1a4f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
