"""Auth, Tenant tablolari ve tenant_id eklendi

Revision ID: bf7ccd79ca7b
Revises: 9c29df5f2fe3
Create Date: 2026-08-21 23:11:13.041742

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf7ccd79ca7b'
down_revision: Union[str, None] = '9c29df5f2fe3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
