"""add taste_vector to customers

Revision ID: c3e9c15caf30
Revises: 82a7617183aa
Create Date: 2026-08-20 15:02:27.288689

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector


# revision identifiers, used by Alembic.
revision: str = 'c3e9c15caf30'
down_revision: Union[str, None] = '82a7617183aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('taste_vector', pgvector.sqlalchemy.vector.VECTOR(dim=512), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customers', 'taste_vector')
    # ### end Alembic commands ###
