"""Tezgahtar (Staff) tablosu eklendi

Revision ID: e31ac01a621f
Revises: 9af5c9bad4f7
Create Date: 2026-08-21 22:33:22.312676

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e31ac01a621f'
down_revision: Union[str, None] = '9af5c9bad4f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
