"""Müşteri telefon alanı için unique kısıtı eklendi

Revision ID: f4b9bc546137
Revises: fa2c9c1e23d7
Create Date: 2026-08-21 22:51:11.599730

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4b9bc546137'
down_revision: Union[str, None] = 'fa2c9c1e23d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
