"""Musteriler (Customers) tablosu eklendi

Revision ID: f8e7b48fdecc
Revises: 7801795f1d9d
Create Date: 2026-08-21 22:41:18.141428

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f8e7b48fdecc'
down_revision: Union[str, None] = '7801795f1d9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('base_tenant_customers', 'vektorEtiketleri',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('base_tenant_customers', 'begenilenUrunler',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('base_tenant_customers', 'begenilmeyenUrunler',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('base_tenant_customers', 'begenilmeyenUrunler',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('base_tenant_customers', 'begenilenUrunler',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('base_tenant_customers', 'vektorEtiketleri',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    # ### end Alembic commands ###
